### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [maksimKorzh/african-food#1]
hi @maksimKorzh  I am a graphic artist and I would like to contribute to your project by designing a logo to it for free. If you are interested, I will begin my design asap. Hoping for your positive feedback. Best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by maksimKorzh** [comment]
@Tobaloidee that would be just great! Mo will be happy))) I wish I could give you something back for it, but I'm maintaining this project almost for free myself, but it's worth of it, so yeah, the logo is just fantastic idea! Waiting to see it!

**Comment by Tobaloidee** [comment]
I am just happy to be able to contribute to projects like this..will show you my initial design here when it's finished. 👍😃

**Comment by maksimKorzh** [comment]
Great! By the way if you have any experience in html/css - there is kind of lots of work to do with that sort of stuff, well even if you don't but want to try it. You know it's cool to work at REAL project, even for free)))

**Comment by maksimKorzh** [comment]
I'll tell Mo(my customer) about your work, he appreciates that! May be even pay you something symbolic.

**Comment by Tobaloidee** [comment]
I'm done with the design @maksimKorzh  but my laptop gave up..repairing it now.😅 will post it here later today..

**Comment by Tobaloidee** [comment]
Whew, good thing i was able to fix it..Here's what i came up with. I hope you like it. Still open for your suggestions 😃

- I created an eye catchy, memorable and simple design which I think will represent your project very well.

![pres-01](https://user-images.githubusercontent.com/36028424/56074225-23bb1a00-5de1-11e9-9ae5-e85c7a90b775.png)

**Comment by maksimKorzh** [comment]
Fantastic @Tobaloidee  it's just great, I'll show this to Mo, think he'll like it! Great job! By the way you know what... probably it would be better if you mail it him yourself, here's his email: chosenveritas@gmail.com\
May the only thing to change is to adjust colors some how in order to match the current color scheme: https://african-food.herokuapp.com/
Kind of make the colors a little bit more solid, well, actually it's Mo to choose, not me, so settle the things down with him directly and then please mail me the approved version to freesoft.for.people@gmail.com

**Comment by maksimKorzh** [comment]
Btw, @Tobaloidee, I'm just curios - do you have any gigs on Fiverr as a designer? You have a great taste, conceptual thinking and catch the very gist of things, you know, people used to pay for this. This little logo definitely costs at least 15$. I'm trying to sell on Fiverr, not that successful there for now(((. So I have a business proposal to you - I can make a decent side and deploy it at heroku in order to give you an ability to PROMOTE YOURSELF as a DESIGNER, how about that? I'll do that for a symbolic fee... and good seller review on Fiverr? How about that, are you interested?

**Comment by maksimKorzh** [comment]
And one more thing, @Tobaloidee, I really like your style hence I have a proposal to work in cooperation - I'm full-stack web-developer you're designer, we could've done a lot of cool things together! I can't pay you, but my future customers would definitely pay for such a reasonable work that you can provide, so how about that?

**Comment by Tobaloidee** [comment]
Hello @maksimKorzh  Sorry for the late response..I went out for work. :) I have emailed Mo the design just now..About fiverr actually I have an account made last year but nobody contacted me. haha! I did not spend time to fix my account there as I have been busy contributing here on Github. But that was very nice of you..

**Comment by Tobaloidee** [comment]
I specialized my craft in logo designing and some photoshop editing..I am glad that you liked my style as a designer. :) 😃

**Comment by Tobaloidee** [comment]
Mo already replied to me on gmail and he said he already have someone researching for him about the logo for his project @maksimKorzh  . Thanks for your positive responses Sir! I appreciate it.

**Comment by maksimKorzh** [comment]
@Tobaloidee sorry for disappointing you I didn't know Mo already has somebody. Take care.
